apiVersion: v1
kind: Service
metadata:
  name: iris-api
  namespace: iris
  labels:
    app: iris-api
spec:
  type: LoadBalancer
  loadBalancerIP: 130.211.219.197   # ðŸ‘ˆ your static IP
  selector:
    app: iris-api
  ports:
    - name: http
      port: 80
      targetPort: 8080
